# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
env:
  parameter-store:
    Login: sonartoken
    Host: Host
    Username: username
    Password: password
    Project: sonarproject

phases:
  install:
    runtime-versions:
      nodejs: 10  
    commands:
      #- echo Installing Mocha...
      #- npm install -g mocha
      
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      #- npm test
      #- npm install
      #- npm install -g snyk
      #- snyk test 
      #- snyk monitor
      #- echo snyk test success
      - npm install -g sonarqube-scanner
     
      #- aws s3 cp s3://$bucket/sonar-project.properties . 
      #- chmod +x sonar-project.properties  
 
      - sonar-scanner -Dsonar.host.url=$Host -Dsonar.login=$Login -Dsonar.login=$Username -Dsonar.password=$Password -Dsonar.sources=src/components -Dsonar.coverage.exclusions=src/**/*test*,src/data/**,src/routes/**,**/*Utils* -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info -Dsonar.javascript.file.suffixes=.js,.jsx -Dsonar.projectKey=REACT_JEST  
      

      #- curl -u $Username:$Password $Host/api/qualitygates/project_status?projectKey=$sonarproject >result.json
      #- cat result.json
      #- OUTPUT="$(jq -r '.projectStatus.status' result.json)"
      #- echo $OUTPUT
      #- |
       # if [ "$OUTPUT" != "OK" ] ;
        #then
        #{
         #echo "Build failed due to SonarQube quality gate failure";
         #exit 1;
         #}
        #fi

 
